### ISSUE TITLE
Suggestion: seperating library into submodule

### ISSUE THREAD

**Issue by patrickjahns** [SmingHub/SmingRTOS#107]
Currently it seems that sming and the libraries are very closely tied together.

I`d suggest seperating the library (libraries) folder from Sming and hosting either them in a seperate github repository.

We could use git submodules to link the libraries with the sming project. 

it has the advantages of being able to update each seperately - new libraries or bugfixes in libraries are not dependant on the Sming repository / or a Sming release

Any thoughts on this?

**Comment by hreintke** [comment]
@patrickjahns : 
I already restructured the directory structure within SmingRTOS to give the libraries a more logical location. 
I would like to keep out of the additional complexity of submodules and having multiple github repo's. 
The number of  bugfixes for the libraries in very limited.

**Comment by patrickjahns** [comment]
Thanks for clarification - I close it for now. 
I think this might be relevant again when we further proceed with platform.io - they seperate frameworks and libraries
