### ISSUE TITLE
Replace SMING_HOME by SMINGRTOS_HOME to avoid messing up with SMING_NONOS

### ISSUE THREAD

**Issue by susie-derkin** [SmingHub/SmingRTOS#118]
Hi,

in order to prevent mixing up the code of Sming_NONOS and Sming_RTOS maybe it would be a god idea to avoid similar environment variables names in both SMING_NONOS and SMING_RTOS.

In order to test hreintkes new code for ftp server which is only in SMING_RTOS i just did this.
But to be honest, I am not sure if this is enough to avoid a mix up. Of course I also generated a new eclipse workspace and checked, that ESP_HOME need not to be modified because SDK_BASE is built by SDK_BASE  ?= $(ESP_HOME)/ESP8266_RTOS_SDK.
The examples work....but not ftp server.

So may be this would be an idea for future commits, if more people would agree.

Thanks in advance

**Comment by hreintke** [comment]
The idea was/is to ease the conversion to SmingRTOS.

The difference beween RTOS and NONOS is that 
- SDK_BASE needs to be defined separate.
- SMING_HOME should point to an RTOS version
