### ISSUE TITLE
Reset during serial callback processing

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#12]
Probably the Serial Update from Sming_NONOS will solve the issue.
Has to be refactored as the NONOS patch is SDK dependent.

Will solve asap.

**Comment by hreintke** [comment]
Hi,
I finished the HardwareSerial implementation, tested working in the basic_serial and works OK now.

But, when compiling the basic_rboot I get again the "include trouble" .
HardwareSerial now needs freertos inlcudes (for task & queue), that interferes with the vPortFree and pvPortMalloc. Did not get it to compile OK yet.

Don't know yet how to create pull requests to the github repo from my local clone. 
And I cannot fork my own repo, but from local merges direct.
That is why I now pushed the solution to a separate branch. 

Will work further solving the include issue.

**Comment by raburton** [comment]
Just merge it over and I'll have a look at the broken sample.

**Comment by raburton** [comment]
```
raburton@debian:~/dev/Sming_RTOS_POC/samples/Basic_rBoot$ make
OC out/build/libmain2.a
make -C /home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/rboot
make[1]: Entering directory '/home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/rboot'
CC rboot-stage2a.c
LD /home/raburton/dev/Sming_RTOS_POC/samples/Basic_rBoot/out/build/rboot-stage2a.elf
E2 /home/raburton/dev/Sming_RTOS_POC/samples/Basic_rBoot/out/build/rboot-hex2a.h
CC rboot.c
LD /home/raburton/dev/Sming_RTOS_POC/samples/Basic_rBoot/out/build/rboot.elf
E2 /home/raburton/dev/Sming_RTOS_POC/samples/Basic_rBoot/out/firmware/rboot.bin
make[1]: Leaving directory '/home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/rboot'
C+ app/application.cpp
In file included from /home/raburton/dev/ESP8266_RTOS_SDK/include/freertos/FreeRTOS.h:87:0,
                 from /home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/SmingCore/SmingCore.h:13,
                 from app/application.cpp:2:
/home/raburton/dev/ESP8266_RTOS_SDK/include/freertos/portable.h:366:34: error: declaration of C function 'void* pvPortMalloc(size_t)' conflicts with
 void *pvPortMalloc( size_t xSize ) PRIVILEGED_FUNCTION;
                                  ^
In file included from include/user_config.h:29:0,
                 from app/application.cpp:1:
/home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/include/esp_systemapi.h:75:14: error: previous declaration 'void* pvPortMalloc(size_t, const char*, uint32_t)' here
 extern void *pvPortMalloc(size_t xWantedSize, const char *file, uint32 line);
              ^
In file included from /home/raburton/dev/ESP8266_RTOS_SDK/include/freertos/FreeRTOS.h:87:0,
                 from /home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/SmingCore/SmingCore.h:13,
                 from app/application.cpp:2:
/home/raburton/dev/ESP8266_RTOS_SDK/include/freertos/portable.h:367:26: error: declaration of C function 'void vPortFree(void*)' conflicts with
 void vPortFree( void *pv ) PRIVILEGED_FUNCTION;
                          ^
In file included from include/user_config.h:29:0,
                 from app/application.cpp:1:
/home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/include/esp_systemapi.h:78:13: error: previous declaration 'void vPortFree(void*, const char*, uint32_t)' here
 extern void vPortFree(void *ptr, const char *file, uint32 line);
             ^
/home/raburton/dev/Sming_RTOS_POC/ESP_RTOS_POC/Makefile-rboot.mk:400: recipe for target 'out/build/app/application.o' failed
make: *** [out/build/app/application.o] Error 1
```

So that's the problem I had before, and the opposite of the original problem you were having, right? I commented these out originally because of the duplicate definition, but for you they were undefined so you needed them in there. Now they need to come out again! I've pushed the fix to this branch. If you're happy, can you PR to master so I can work on the case changes.

**Comment by hreintke** [comment]
Just updated the repo. Hope I did it OK. First time ever :smile: 

With master branch now, I have the user_interface.h issue. 
This file was also not in the alt-sdk from kireevco.

Is the esp-open-sdk somewhere available as binary (Linux is OK) so I can check the differences of include files with my toolchain

**Comment by hreintke** [comment]
HardwareSerial issue solved.
Basic_rboot discussed in another issue
