### ISSUE TITLE
mqtt.commandProcessing()?

### ISSUE THREAD

**Issue by samschaerer** [SmingHub/SmingRTOS#120]
Hello

What does 

> mqtt.commandProcessing(true,"command","cmdreply")

 on line 76 in the sample _MqttClient_Hello_ exactly?

Thanks

**Comment by hreintke** [comment]
It is the integration of CommandProcessing and MQTT.

mqtt.CommandProcessing (
true/false -> enable/disable for this mqtt object
"command" -> the topic which contains command that will be executed
"cmdreply" -> the topic that will be used to send the result of the command

**Comment by samschaerer** [comment]
Thanks for the explanation
