### ISSUE TITLE
Using flashstream

### ISSUE THREAD

**Issue by samschaerer** [SmingHub/SmingRTOS#122]
Hi @hreintke 

Is there an example of the "flashstream option" you mentioned in [this post](https://github.com/SmingHub/Sming/issues/711)?

Thanks

**Comment by hreintke** [comment]
The rBoot_Generic sample has the flashstream functionality inlcuded.
Also some explanation int the readme.txt

**Comment by samschaerer** [comment]
Ok, thank you. I will check it out
