### ISSUE TITLE
Are there any plans to add mDNS support?

### ISSUE THREAD

**Issue by ericmnel** [SmingHub/SmingRTOS#123]
and will it be available before the esp32 ships?   mDNS was the one thing that I use that stopped being available when I switched from Sming to SmingRTOS.

**Comment by hreintke** [comment]
@ericmnel : 
I did not leave anything specific when moving from SmingNONOS to SmingRTOS.
Can you point me to the mDNS support location ?

**Comment by ericmnel** [comment]
I don't think that the RTOS SDK has mDNS support the way that the NONOs SDK did, and nobody at espressif seems to reply to questions about it.   I am guessing we will have to write our own.

At some point I might get the time to write one and submit it for your review, probably using the Arduino MDNS code as an example to copy, but I was hoping somebody else was already working on it.

**Comment by hreintke** [comment]
Not supported by Espressif RTOS SDK
