### ISSUE TITLE
basic_rboot compile issue

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#13]
@raburton : 
I needed to add (SMING_HOME)/system as extra include to makefile-rboot to compile on my system.

Did you compile before without issues ?
Should we get rboot-api.c out of the application make and into libsming ?

PS : I tried to make a PR instead of direct merge. Still learning on the git(hub)

**Comment by raburton** [comment]
Compiles fine on mine without that. What was it missing?

**Comment by hreintke** [comment]
I get a include file not found on osapi.h

**Comment by raburton** [comment]
removed this include file, and updated rBoot generally
include files for this system are a mess (not entirely our fault), does adding in the extra path you did earlier have any other consequences? (that folder includes various other things too)

**Comment by hreintke** [comment]
No,  adding the path did not had consequences on first sight. 
All still compiles ok. Will see running when I update the HardwareSerial Callback.

On include files, do you mean contents of include file or the path locations of them. Probably both ?
For locations : do you suggest a relocation ? If so, just for the compiler/include/.., include/.., system/include/... and so on, or also the .h files from SmingCore ?

Related : Should we rename all to lower case file names as you suggested in Sming NONOS.

**Comment by hreintke** [comment]
After your revert of rboot. I get a include file missing on user_interface.h in rboot-api.c
Changing that "back" to my initial osapi.h & spi_flash.h it compiles again.
Just adding user_interface.h to my project gives me implicit declaration errors.

Both osapi and user_interface are include files which only exist in nonos sdk and not in rtos sdk.
What is the best way to go. Copy user_interface.h in the project and solve the issues or try to get one (1) project specific include file where we put all missing defines/function prototypes ?

**Comment by raburton** [comment]
There is a user_interface.h that comes with the compiler, I assume I must be picking that up. It seems to work. I guess windows doesn't have this with the compiler, or doesn't look at the compiler includes?

**Comment by hreintke** [comment]
So there is the difference with the environments. There is no user_interface.h with the compiler.

Besides that I included the -v option in the gcc compile. Displays search tree. 
Result for rboot-api.c below   

Will check further, also on the toolchain from kireevco, arduino/esp8266, esp-open-sdk.

```
gcc version 5.1.0 (GCC) 
COLLECT_GCC_OPTIONS='-v' '-I' 'app' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode' '-I' 'app/include' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode/include' '-I' 'include' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/include' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/compiler/include' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/system/include' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/system' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/Wiring' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/Libraries' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/SmingCore' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot' '-I' 'c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/extra_include' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include/lwip' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include/lwip/ipv4' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include/lwip/ipv6' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include/freertos' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include/espressif' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include/espressif/esp8266' '-I' 'C:/Espressif/ESP8266_RTOS_SDK/include' '-Os' '-g' '-Wpointer-arith' '-Wundef' '-Werror' '-nostdlib' '-mlongcalls' '-mtext-section-literals' '-finline-functions' '-fdata-sections' '-ffunction-sections' '-D' '__ets__' '-D' 'ICACHE_FLASH' '-D' 'ARDUINO=106' '-D' 'BOOT_BIG_FLASH' '-D' 'WIFI_SSID="FRITZ!Box Fon WLAN 7360"' '-D' 'WIFI_PWD="00163262000955166948"' '-D' 'SPIFF_SIZE=65536' '-D' 'RBOOT_SPIFFS_0=0x100000' '-D' 'RBOOT_SPIFFS_1=0x300000' '-D' 'RBOOT_INTEGRATION' '-c' '-o' 'out/build//C/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode/rboot-api.o'
 c:/espressif/xtensa-lx106-elf/bin/../libexec/gcc/xtensa-lx106-elf/5.1.0/cc1.exe -quiet -v -I app -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode -I app/include -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode/include -I include -I c:/Userdata/RTOS_Project/ESP_RTOS_POC -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/include -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/compiler/include -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/system/include -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/system -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/Wiring -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/Libraries -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/SmingCore -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot -I c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode -I C:/Espressif/ESP8266_RTOS_SDK/include -I C:/Espressif/ESP8266_RTOS_SDK/extra_include -I C:/Espressif/ESP8266_RTOS_SDK/include/lwip -I C:/Espressif/ESP8266_RTOS_SDK/include/lwip/ipv4 -I C:/Espressif/ESP8266_RTOS_SDK/include/lwip/ipv6 -I C:/Espressif/ESP8266_RTOS_SDK/include/freertos -I C:/Espressif/ESP8266_RTOS_SDK/include/espressif -I C:/Espressif/ESP8266_RTOS_SDK/include/espressif/esp8266 -I C:/Espressif/ESP8266_RTOS_SDK/include -iprefix c:\espressif\xtensa-lx106-elf\bin\../lib/gcc/xtensa-lx106-elf/5.1.0/ -D __ets__ -D ICACHE_FLASH -D ARDUINO=106 -D BOOT_BIG_FLASH -D WIFI_SSID="FRITZ!Box Fon WLAN 7360" -D WIFI_PWD="00163262000955166948" -D SPIFF_SIZE=65536 -D RBOOT_SPIFFS_0=0x100000 -D RBOOT_SPIFFS_1=0x300000 -D RBOOT_INTEGRATION c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode/rboot-api.c -quiet -dumpbase rboot-api.c -mlongcalls -mtext-section-literals -auxbase-strip out/build//C/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode/rboot-api.o -g -Os -Wpointer-arith -Wundef -Werror -version -finline-functions -fdata-sections -ffunction-sections -o C:\Users\Herman\AppData\Local\Temp\ccDHb5AL.s
GNU C11 (GCC) version 5.1.0 (xtensa-lx106-elf)
    compiled by GNU C version 4.8.1, GMP version 6.0.0, MPFR version 3.1.2, MPC version 1.0.2
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "c:\espressif\xtensa-lx106-elf\bin\../lib/gcc/xtensa-lx106-elf/5.1.0/../../../../xtensa-lx106-elf/sys-include"
ignoring duplicate directory "c:/espressif/xtensa-lx106-elf/lib/gcc/../../lib/gcc/xtensa-lx106-elf/5.1.0/include"
ignoring duplicate directory "c:/espressif/xtensa-lx106-elf/lib/gcc/../../lib/gcc/xtensa-lx106-elf/5.1.0/include-fixed"
ignoring nonexistent directory "c:/espressif/xtensa-lx106-elf/lib/gcc/../../lib/gcc/xtensa-lx106-elf/5.1.0/../../../../xtensa-lx106-elf/sys-include"
ignoring duplicate directory "c:/espressif/xtensa-lx106-elf/lib/gcc/../../lib/gcc/xtensa-lx106-elf/5.1.0/../../../../xtensa-lx106-elf/include"
ignoring nonexistent directory "app/include"
ignoring nonexistent directory "c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode/include"
ignoring duplicate directory "c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode"
ignoring duplicate directory "C:/Espressif/ESP8266_RTOS_SDK/include"
#include "..." search starts here:
#include <...> search starts here:
 app
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot/appcode
 include
 c:/Userdata/RTOS_Project/ESP_RTOS_POC
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/include
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/compiler/include
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/system/include
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/system
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/Wiring
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/Libraries
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/SmingCore
 c:/Userdata/RTOS_Project/ESP_RTOS_POC/rboot
 C:/Espressif/ESP8266_RTOS_SDK/include
 C:/Espressif/ESP8266_RTOS_SDK/extra_include
 C:/Espressif/ESP8266_RTOS_SDK/include/lwip
 C:/Espressif/ESP8266_RTOS_SDK/include/lwip/ipv4
 C:/Espressif/ESP8266_RTOS_SDK/include/lwip/ipv6
 C:/Espressif/ESP8266_RTOS_SDK/include/freertos
 C:/Espressif/ESP8266_RTOS_SDK/include/espressif
 C:/Espressif/ESP8266_RTOS_SDK/include/espressif/esp8266
 c:\espressif\xtensa-lx106-elf\bin\../lib/gcc/xtensa-lx106-elf/5.1.0/include
 c:\espressif\xtensa-lx106-elf\bin\../lib/gcc/xtensa-lx106-elf/5.1.0/include-fixed
 c:\espressif\xtensa-lx106-elf\bin\../lib/gcc/xtensa-lx106-elf/5.1.0/../../../../xtensa-lx106-elf/include
End of search list.
```

**Comment by raburton** [comment]
`-v` doesn't show that on mine so I can't compare, but then I have gcc 4.8.2 so that's another difference.

**Comment by raburton** [comment]
Re earlier questions about include files... I mean that it's not clear what includes what, and where it includes it from, and there are so many different include files with the same that you need to get the includes list in the right order and specify the path carefully on the #include to get the right one. And then people are potentially getting the wrong one even then, do to some difference in their environment. This is partly espressifs fault, not just ours.

On the case question, yes I think we should lower case all the directories. I'm not opposed to mixed case in the filenames though, since they generally follow the c++ class names and have more complex names. I can easily lowercase the ones that aren't currently if you like, I've done it here and made the changes to where they are used (as the #include needs to be updated for case-sensitive filesystems) and all seems well.

Richard.

**Comment by hreintke** [comment]
On include files.
Would it help to get all the sming/system includes in a very limited number of directories ? 

sming/include -> just for user_config
sming/include/espressif -> include files from espressif
sming/include/espressif/sdk -> modified includes from espressif sdk
sming/include/sming -> sming specific includes -> smingcore.h, wiringframeworkdependencies and other includes which are needed for sming applications

Then we will have a more limited search path and hopefully can identify issues better.

**Comment by hreintke** [comment]
On lower case -> Let's do it. 
The libraries are coming in now and then can be updated ti use them too.

**Comment by hreintke** [comment]
Richard,
After you last update on rboot-api I got again the user_interface.h issue.
Trying to use the one from nonos sdk or replacing by other includes revealed the include nightmare to its extend.

By updating in rboot-api from os-malloc/os-free to malloc/free I could remove user_interface.h & mem.h Adding spi_flash from rtos sdk included the necessary spi functionality.

I don not know why (and surely not criticize) you are using the os_malloc variant.
I know in sming there is also use of malloc.

As I am still not able to make PR's on my own repo, used the branch method again to show you the updates I made to get basic_rboot working like a charm.

Please comment

**Comment by raburton** [comment]
That's odd, I didn't think I'd updated rboot-api.c again after your last change to the headers. Sorry if a new version slipped in there! The problem is trying to keep upstream working in both nonos and rtos without making custom changes in sming (except in rboot-integration.h, which is for this purpose). We don't really want to have to touch third part things, like rBoot, so they are easier to update (especially with things that are platform specific and so might not immediately be noticed by the uploader). If there was an easy way to know which you were being compiled with then #ifdef could be used. Is there an easy way to detect you are building with rtos?

**Comment by hreintke** [comment]
What I recall from our previous trials is (not completely sure as many things happened) 
- I initially included a wrong version in rtos sming
- In order to make that compile, I updated it it use to osapi but also needed to uncomment some lines in esp_systemapi. 
- You updated the rboot to revert my experimental changes.
- I had the original user_interface issues, which I solved temporary in the same as above
- I updated hardwareserial which also caused my version not compiling, similar but other issues than before -> I could not get it done and made the branch
- You solved that issue but that also included the user_interface 
- With your updated version as base I got it to work again but that is using "local updates" on your generic rboot.

Sure there can be a way to detect RTOS usage. When we want to implement ESP32 there will also be the need for "knowing for which sdk to compile" I presume to define something like "RTOS8266" or "RTOS" and "ESP8266".

For now I see a solution in defining a "USE_LOCAL_INCLUDES" in rboot-integration, and surround the includes in rboot-api with ifndef's of that.
I hope/think I also can get around the os_malloc & os_free usage in rboot-api.

This would give a solution for now with minimal and non-intrusive updates to upstream rboot, and probably also useful when esp32 arrives. 

Will check further.

**Comment by raburton** [comment]
The odd thing is that this seems to be a different problem to before. Previous issues seemed to be 1) duplicate definitions (locally defined things that were also defined in the somewhere sdk, although not picked up on Windows), these became an issue on windows too after updating hardware serial and including platform.h in the smingcore.h, easily fixed by removing the local definition and just taking the one from portable.h on all platforms. 2) Missing user_interface.h on windows, which you previous fixed by swapping this #include for spi_flash.h and this worked on linux and windows (and I appear to have accidentally undone this change).

This issue of os_malloc/os_free seems to be new and I have no idea where that's come from. They are also defined locally in sming, in mem.h so maybe that was being pulled in before but for some reason isn't now. This is part of the include mess, we need to get rid of as many overridden include files as we can, as they probably aren't needed now anyway, so we actually know what's getting used.

**Comment by hreintke** [comment]
In frustration of "getting something to compile" I removed the mem.h from rboot-api.c
Inclusion leads again to ``error: implicit declaration of function 'pvPortMalloc'` and others. The earlier solution for that doesn't work anymore.
I just did not know how to solve otherwise. Hope it doesn't lead to more frustration on your side.

Do you have a proposed way to get out of the include mess ? 
I am happy to work on that but would need some direction from you. 

That also prevents that we both work on different solutions which creates Mess V2.0

**Comment by hreintke** [comment]
Richard,
The Basic_rboot (rboot-api) compiles in my environment OK when I include 

```
#include "projdefs.h"
#include "portable.h"
```

in the rboot-integration.h.
Can you check whether that is also OK at yours ?

**Comment by raburton** [comment]
Including these files is fine on Linux, but can I suggest:

```
#include <freertos/projdefs.h>
#include <freertos/portable.h>
```

**Comment by hreintke** [comment]
Solved by Richard last commit
