### ISSUE TITLE
How to migrate from Non-OS Sming to RTOS Sming in Windows?

### ISSUE THREAD

**Issue by williamesp2015** [SmingHub/SmingRTOS#130]
I have deleted Non-OS Sming and replaced with RTOS in Sming directory, then deleted ESPressif\sdk and Created directory link  to ESP8266_RTOS_SDK directory, then rebuilt index, build all. Unfortunately, I have problem with all the applications. Please someone write an instruction to ease the migration from Sming Non-OS.

**Comment by hreintke** [comment]
@williamesp2015 : 
I will do but for now : 
- Remove the user_config.h include file
- If using spiffs_mount_ manual, decrease the address by 0x402000
- For includes in the application, just include SmingCore.h, all Sming excluding libraries are then availabl

**Comment by williamesp2015** [comment]
Thank you. I deleted previous SmingRTOS and copied a fresh copy, then made a bath file:
REM Run as Administrator
CD\
CD c:\tools\sming\sming
make
CD spiffy
make
del c:\Espressif\sdk
mklink /d c:\Espressif\sdk c:\Espressif\ESP8266_RTOS_SDK
///////////////////
Then made esptool2 and PATH variables in the Eclipse Environment Variables
Then rebuild and then build all but there is persistant previouse errors:
Function 'digitalWrite' could not be resolved   application.cpp /Basic_Blink/app    line 11 
Method 'initializeMs' could not be resolved application.cpp /Basic_Blink/app    line 18 Method 'start' could not be resolved    application.cpp /Basic_Blink/app    line 18 
///////////////////////
All the Sming variables and path in the Windows variables are correct as Sming Non-OS.

**Comment by hreintke** [comment]
No need to do the mklink but if you do you should do it before the make's.
Now you are building Sming against NONOS sdk.

Better to use the environment variable SDK_BASE.
If you set that to : C:/Espressif/ESP8266_RTOS_SDK (forward slash !, don't know how to solve that), the make files will use the correct SDK
You can set that also within your eclipse
