### ISSUE TITLE
Sample app for storing configuration settings

### ISSUE THREAD

**Issue by helpme1** [SmingHub/SmingRTOS#136]
I have been using HttpServer_ConfigNetwork as a sample app for reference on how to store configuration settings on SMING NONOS. For SmingRTOS, HttpServer_ConfigN etwork app is missing. Which is the closest sample app in SmingRTOS that I can use as reference on how to store configuration settings?

**Comment by hreintke** [comment]
@helpme1 : 
Just added the HttpServer_Config example to SmingRTOS.
Did not test but should work identical to SmingNONOS.

Please feedback on usage.

**Comment by helpme1** [comment]
Thank you very much for your quick action.

**Comment by helpme1** [comment]
I have tested your newly added HttpServer_Config example. So far, so good. Thanks!
