### ISSUE TITLE
Initial issues

### ISSUE THREAD

**Issue by raburton** [SmingHub/SmingRTOS#2]
Made a PR for compiling on Linux, but still got issues...
1) Missing libs microc & microgcc
2) If I add these from Sming I get error: `multiple definition of 'abort'`
3) Missing linker script

**Comment by raburton** [comment]
Ok, found the new lib files and made a few more changes to enable complete compilation. I'll leave this issue open for the moment though, to save keep opening new ones if I get more problems.

**Comment by hreintke** [comment]
@raburton : 
I forked the microc repository under my account and committed the update I made to it to get SmingRTOS working.
https://github.com/hreintke/esp_microc.git
