### ISSUE TITLE
Include file restructuring

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#20]
I made a copy of most of the include files used within sming_RTOS.

Left out the Services as they come from other upstream.
Did not (yet?) decapitalize all filemames, but think is better to do.

Benefit : 
Clear include file structure which give the possibility to know/control the search path
All includes in one directory, improves on the possibility to release a "binary package" with just include files and sming framework

Please comment.
If we agree I will take the action to do this change in RTOS_Sming and adapt the includes in the source files.

I had to change the extension to txt to be able to attach -> change back to zip for usage
[sming_includes.txt](https://github.com/hreintke/Sming_RTOS_POC/files/80026/sming_includes.txt)

**Comment by raburton** [comment]
I don't think we should lower case the filenames, at least not for the most part. Certainly not the C++ classes. The purely C ones, the glue etc. things like esp_systemapi.h that's fine, but the C++ user facing headers should remain mixed case like the class names. The rboot-integration.h doesn't really want to go into a separate rboot folder, it's just a bit more glue and being in it's own folder this would have to be added extra to the include path with already has a lot of entries. My main suggestion would be to separate the user c++ include files from the internal stuff. So user c++ headers would all be `#include <Sming/xxx.h>` and the internally used c headers would be in the parent include folder. Also, remember where we are overriding a header that the path and file names and cases must be the same or we won't get the override we are expecting.

**Comment by hreintke** [comment]
The separation of c++ and internal stuff was also one of my goals.
I hope that an application would only include "smingcore.h" and then can use all functionality.
Did a little more restructuring in attached.

I made a specific directory rot rboot as it also a "main subdirectory" 
Looking at the other components  and keep it identical we can move the rboot directory as a whole to Services.
All services directories have their include and integration files in the same directory.
That would leave all rboot source and include file together.

Am aware of the specific issues with overriding headers, I used rtossdk for it.
Now renamed to local_overrides. subdirectories and include filenames in there should follow naming of overridden files.

See attached for adapted version. 

[sming_includes_2.txt](https://github.com/hreintke/Sming_RTOS_POC/files/80128/sming_includes_2.txt)

**Comment by raburton** [comment]
Looks better. Can't move rBoot to services, because they all get compiled into libsming automatically and the rBoot folder shouldn't be treated in this way. Also, the rBoot integration header should stay with the Sming header glue, not in the rBoot folder, so that rBoot remains untouched upstream source (and potentially can even be made a git submodule).

**Comment by hreintke** [comment]
OK, clear.
I have second thoughts on timing for the Sming c++ classes.
My current understanding is that we need to keep that structure when we want to use the patch files from PR's of Sming_NONOS to get Sming_RTOS on the same level.
If that is true we better can take this action as one of the latest  -> correct ?

For the others, shall I move and update the #include " ....h" line in the files which use them ?
If so, do I need a special action so that git/github sees it as a move and not remove and add a new file?

**Comment by raburton** [comment]
Yes, it'll be harder to compare the version for applying updates from upstream Sming. But it's probably already not that easy. Probably the best option is to go through all the commits since branching and, if they apply, manually applying them to the rtos version. There will be a good few of them, but for the most part not that big. Bug fixes are generally pretty small and new things are probably in their own files. Not sure what there has been a lot of significant changes in sming recently. Once up to date it would probably be wise to watch for merges and port them at the time.

**Comment by hreintke** [comment]
Richard,

I just pushed a branch Restructure_Include_Sming.

In there I have : 
- put the system include files on the location we discussed above
- restructures sming source directory
- updated the sming framework makefile, removed all the unnecessary include paths.
- updated the sming & library files to have only #include lines which are relative to the search paths in the makefile. 

That should give a clear understanding of the search paths -> which include paths are taken.

These are the include directories which are still in 

```
EXTRA_INCDIR =  $(SMING_HOME)/sming
EXTRA_INCDIR += $(SMING_HOME)/include
EXTRA_INCDIR += $(SMING_HOME)/rboot 
EXTRA_INCDIR += $(SMING_HOME)/rboot/appcode
EXTRA_INCDIR += $(SMING_HOME)/services
EXTRA_INCDIR += $(SMING_HOME)/libraries
```

I have been doubting whether it should be even : 

```
EXTRA_INCDIR =  $(SMING_HOME)/
EXTRA_INCDIR += $(SMING_HOME)/include
```

Will think that over, would need another go over the sourcef files but will do that if it improves even more.

What is your opinion on the above ?
If we agree on this, I will also update the makefile-project & makefile-rboot to get identical search paths for applications.

**Comment by raburton** [comment]
I'm playing with the branch, but I don't like the main sming include files being pushed down another directory called "core" it just means everything needs an extra bit of path. The core stuff should be in sming, separate non-core parts in subdirs. Think about how you use these as includes. `#include <sming/SomeCoreFeature.h>` makes more sense than `#include <sming/core/SomeCoreFeature.h>`

**Comment by hreintke** [comment]
I disagree with you on this, I deliberately pushed the core down own level.
It's the paradigm : don't put sources and subdirectories on one level, you loose overview on what is in.  Compare with the sming and samples on one level -> no overview what is in.
It makes development environment unnecessary unclear, and I can tell you from personal experience.
about includes : who is really using the includes : the actual sming developers, and the number of them is really limited. People building applications are just including SmingCore.h and they are done.

**Comment by hreintke** [comment]
I updated the branch with further improvements.
include path is now limited to : 

```
EXTRA_INCDIR =  $(SMING_HOME)/
EXTRA_INCDIR += $(SMING_HOME)/rboot
```

The rboot needs to be in due to the rboot-api.h which includes <rboot.h> -> include path dependent.
For application IDE's the configuration of include path's is easy.

For user_config : 
I added esp_systemapi.h to SmingCore.
This gives the situation that a user_config can be empty.

In the SmingCore.h I include sming_config.h 
In there we can set all value which can be overridden by user in user_config example is SERIAL_BAUD_RATE

Framework compiles OK, applications I will start on now.

**Comment by raburton** [comment]
Few thoughts:
- Agree with adding esp_systemapi.h to smingcore.h, user shouldn't need to include anything but smingcore.h
- But it looks like you now have two copies of smingcore.h in the repo.
- It looks like user_config.h is no longer pulled in by the rtos sdk like it was by nonos sdk, because you've got rid of it and it still compiles. So I guess the user app doesn't need one either.
- Using so many path chunks in the #include to find the rboot-api.h just seems like a bit of hack to avoid having the folder on the include path.
- Still not convinced of the need to push files down an extra dir in to core. The suggested layout (includes at top level and in some subfolders) is pretty common for include files. The reason I named that inner directory sming was so that it made sense for includes of <sming/*.h>, but that doesn't really work the same now. There is still logic in calling it sming if all the sming code (as opposed the the libraries, rboot, spiffy, etc) is in there, but if that's the plan appinit needs to move inside sming. Although now I see you are only using the higher director on the include path it does mean everything starts with sming/, so maybe it's not so bad.

**Comment by raburton** [comment]
(both comments updated)
- You still have ets_sys.h & c_types_compatible.h in there, which should be removed.
- The local_overrides folder isn't a great name, especially as it no longer has any overrides in it, just two extra header files.
- Seems odd that if you add the top level dir to the include path there is then an include folder another level down, below sming.

**Comment by hreintke** [comment]
Quick reply, work is in progress but getting more complete.
- smingcore twice. Yes now it is, I was/am not sure whether I need a different smingcore for framework/applications. If so, the "internal one" should be renamed. 
  Probably not in the current extend needed for framework. What I do notice is that most classes need some same includes -> can/should be moved to one. Could use sming_config for that but that is a little strange naming so probably will take another one.
- user_config is not needed anymore for compiling an application. 
  My assumption is that all userconfig items are defines. In sming_core I included sming_config (which is part of the framework).
  In sming_config we can put all configurable defines, surrounded by #ifndef #endif. That guarantees that all items have sensible defaults and can be set at one location. 
  If an application wants to use other settings, he/she can create a user_config (or a include file with any other name) and put his values in there. These will override the sming set defaults.
  We could decide that we add an user_config to each example which does not set any value but shows the possibilities.
- ets_sys & c_types_compatible. 
  The usage is already out. Need to remove the files. I left them in because I am not sure if removing them in here would interfere with merging into master as you already removed them there. 
  Can remove them without issues if that will work OK.
- local_overrides. Something like the above. I was not sure on your actions so just left it in for later decision.
- include directory.
  I was thinking of the toplevel one to be for applications and the one below sming for framework.
  Have not fixed the solution. My expectation is that when I start with the examples I will see how it works out and adapt to that.

More to come...

**Comment by hreintke** [comment]
I pushed a change for s applications compile on the new structure.
Still on the current makefile-project & rboot.
I had to change some includes in the rboot part for that.

I did that just to be able to continue, need to talk with you on final solution

**Comment by hreintke** [comment]
Close to finish now.

I checked the functions in esp_systemapi.h and I think almost all can be removed.
I did and because of the nature of the contents now, I changed the name to sming_globals.

Cleaned the include directory from files we do not use anymore. 
Also without the lwip overrides, it compiles OK. So probably an starting issue.
We could even remove the include/system directory and move the contents to include

Renamed the internal used smingcore to SmingInternals to get rid of the naming conflct.

I included an "empty" user_config.h in the samples directories which had one before.
In this way we would have a location to point to the information on config items.

Update : 
And we need to decide on the rboot includes as mentioned above

**Comment by hreintke** [comment]
@raburton : 
I think I finished the restructuring. 
What I did to be able to merge was (On my local workspace)
- pull master branch to get latest copy
- create a new branch based on master branch -> restructure_3
- Merge the restructure2 branch into restructure_3
- Update Restucture_3 to resolve compile issues.
- Push Restructur_3 to github

Is this OK to be able to merge this into master ?

I have some other issues to solve which I like to do directly in the right place.

**Comment by raburton** [comment]
sure, if there are any remaining issues we can sort them in situ

**Comment by hreintke** [comment]
OK, 
I know you mentioned squashing before merging but I am not sure how to get that done from the branch.
Do I need to make another branch to get the commits squashed then merge ?

**Comment by raburton** [comment]
i've just tested (in a new branch for ease) and it worked ok, see new branch restructure4
you can just go with that if it  looks ok, or squash on your own branch

**Comment by hreintke** [comment]
Done
