### ISSUE TITLE
c_types

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#21]
Richard,
I am porting the other examples.
When compiling I get a lot of undefined types like uint32.
I have seen your remark on gitter regarding c_types_compatible.h
Been struggling already in the initial porting to get out of these. 

Before getting another "temporary working solution" : 
What is your opinion on how/where to include these types ?

**Comment by hreintke** [comment]
Checked further.

I think the types come in thru esp_systemapi.h
which also includes other : 

```
#include <stdarg.h>
#include <stddef.h>
#include <espressif/c_types.h>
#include <espressif/esp8266/ets_sys.h>
#include <espressif/esp_libc.h>

#include <user_config.h>

#include "m_printf.h"
```

Should we split this in a : 
esp_systemapi -> only esp/sdk function which do not have a prototype in the espressif includes
sming_generic -> includes for the standard libraries (need a better naming).

Besides the above, there is a tricky include interference.
Both the user_config.h from application as the user_config.h from framework are on the search path.
Although called user_config, the sming framework doesn't compile without it. In current, the only include from there is esp_systemapi -> rename or just use esp_systemapi when needed.
For application I suppose (needs some testing) we just can include esp_systemapi in smingcore.h which cleans user_config from additional, almost hidden inlcudes.

On both user_configs on the serach path, I assume it was intended to have the "sming user_config" included when no "application user_config is present. 
However, when a new define needed for applications, all application user_configs need to be updated.
I would propose a similar as with makefiles. The user_config sets defines as the app wants and includes a "user_config_project" which has defaults for all supported defines, surrounded by #ifndef #endif for not overriding.

**Comment by raburton** [comment]
Thoughts:
- I think SmingCore.h should #include esp_systemapi.h
- I don't see the need to separate the missing function definitions in esp_systemapi.h from the system header includes, they are both needed and not a lot of point spreading them across two files.
- user_config.h is included by espressif include files, so anything that compiles with the sdk needs to have one. For apps we need to make sure the apps own include dir is earlier in the search path than the standard one, so it overrides the default one. We could change the name of the app user_config or make the file much simpler and have an #include_next at the top to pull in the generic one first, then override with user variables.

**Comment by raburton** [comment]
I think this issue is dealt with now.
