### ISSUE TITLE
undefined reference m_printf

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#26]
in esp_systemapi the debugf(..) id defined.
In sming_nonos it is defined as m_printf(...) and works OK.

For now, in sming_rtos it is defined as printf(...) -> the standard printf
This is not a good solution as it interferes with debug statement in classes derived from the Print class in sming, which also has a class function printf.
Also the    Serial.systemDebugOutput(true); // Debug output to serial will need to be revised (if possible).

When using the m_printf(..), compiling the framework is OK, compiling the examples but..
When linking, a number of `undefined reference to`m_printf'` occur.
Not for all debugf statements, sometimes even for a Serial.printf.

I checked numerous possibilities but cannot find reason or solution.

Anyone of you having an idea or direction to look for ?

**Comment by ADiea** [comment]
@hreintke please attach a build log, no other errors when compiling that may cause mprintf to be undefined? i see it is included in the makefile sming/system Unfortunately i do not have more time these days but attach the log and i'll take a look

cheers

**Comment by hreintke** [comment]
These are the build. Indeed no compile errors for framework or application.

```
.....
C+ libraries/SDCard/SDCard.cpp
C+ libraries/Servo/Servo.cpp
C+ libraries/Servo/ServoChannel.cpp
C+ libraries/Ultrasonic/Ultrasonic.cpp
C+ libraries/dht/dht.cpp
AR build/libsming.a
Installing libsming
Done

08:58:30 Build Finished (took 24s.884ms)
```

But with any application using spiffs I have : 

```
09:02:31 **** Build of configuration Sming for project HttpServer_WebSocket ****
make rebuild 
C+ app/application.cpp
AR out/build/app_app.a
LD out/build/app.out
c:/userdata/rtos_project/sming/compiler/lib/\libsming.a(DataSourceStream.o):(.text._ZN10FileStreamC2E6String+0x8): undefined reference to `m_printf'
c:/userdata/rtos_project/sming/compiler/lib/\libsming.a(DataSourceStream.o): In function `FileStream::FileStream(String)':
C:\Userdata\RTOS_Project\sming/sming/core/DataSourceStream.h:133: undefined reference to `m_printf'
C:\Userdata\RTOS_Project\sming/sming/core/DataSourceStream.h:133: undefined reference to `m_printf'
c:/userdata/rtos_project/sming/compiler/lib/\libsming.a(DataSourceStream.o): In function `HashMap<String, String>::operator[](String)':
C:\Userdata\RTOS_Project\sming/sming/core/DataSourceStream.h:133: undefined reference to `m_printf'
c:/userdata/rtos_project/sming/compiler/lib/\libsming.a(DataSourceStream.o):(.text._ZN18TemplateFileStream15readMemoryBlockEPci+0x7a): undefined reference to `m_printf'
c:/userdata/rtos_project/sming/compiler/lib/\libsming.a(DataSourceStream.o):C:\Userdata\RTOS_Project\sming/sming/core/DataSourceStream.h:133: more undefined references to `m_printf' follow
collect2.exe: error: ld returned 1 exit status
make: *** [out/build/app.out] Error 1

09:02:33 Build Finished (took 2s.552ms)
```

And I just can't find what I am overlooking.

**Comment by hreintke** [comment]
@ADiea : 
Don't want to push your "search" into the same direction I am but...
I think this is (party) caused by the fact that in the RTOS sdk there is a generic printf(..) available and in not in NONOS .

**Comment by hreintke** [comment]
@ADiea : @anakod @slaff @sle118 @raburton  
I really need help on this. 
Have no idea anymore where to search and probably "solution blind" I need another pair of eyes to get it going.

It currently holds moving Sming_RTOS to Beta status as I suspect current debugf using just printf causing unstable behavior.

Just ask what you need to know to start and I will provide it.

**Comment by ADiea** [comment]
Hi
i'm on a tight schedule(as always...) these days cannot setup the project
-> pls attach map file

**Comment by raburton** [comment]
I'm not sure I really understand the problem. The Debug class, which is a subclass of Print, calls printf() in printPrefix() and that correctly calls Print:printf(). It doesn't call sdk printf function instead. That's the right way around isn't it?

**Comment by anakod** [comment]
I think what spiffs enabled applications include some standard C include with printf redefine. It's bad.

But why you don't like use m_printf everywhere instead?

**Comment by hreintke** [comment]
@raburton : Sorry to be unclear in my initial description. Here is a better one.

It concerns the debugf(..) statements in the source.
In include/sming_globals.h it is currently defined 
`#define debugf(fmt, ...) printf(fmt"\r\n", ##__VA_ARGS__)`
That works fine, the output gets printed on Serial as expected.
But.. in this way I cannot stop the debugf output to Serial
For that I need to define debugf as : 
`#define debugf(fmt, ...) m_printf(fmt"\r\n", ##__VA_ARGS__)` -> output using m_printf(..)
m_printf is defined in sming/system m_printf.h & .cpp.
This also the way we redirect debugf within SmingNONOS.

When defined as this m_printf
- Sming complies OK
- Application not using filesystem compile & link OK.
- Applications using filesystem compile OK but giving link errors.

```
LD out/build/app.out
c:/userdata/rtos_project/sming/compiler/lib/\libsming.a(DataSourceStream.o):(.text._ZN10FileStreamC2E6String+0x8): undefined reference to `m_printf'
c:/userdata/rtos_project/sming/compiler/lib/\libsming.a(DataSourceStream.o): In function `FileStream::FileStream(String)':
C:\Userdata\RTOS_Project\sming/sming/core/DataSourceStream.h:133: undefined reference to `m_printf'
```

**Comment by hreintke** [comment]
@anakod : 
I checked the spiffs_sming.h & spiffs_config.h.
There was an #include <stdio.h> in spiffs_config -> removing did not solve the issue.

**Comment by hreintke** [comment]
@anakod : 
I do want to use m_printf() everywhere.

@all : Retesting done just now : I also have applications not using filesystem which have the issue.

**Comment by anakod** [comment]
@hreintke, please check carefully what this branch isn't called/used:
https://github.com/SmingHub/Sming/blob/develop/Sming/Services/ArduinoJson/src/Arduino/String.cpp#L11
(non defined ARDUINO def)
I'm not very like this solution.

**Comment by raburton** [comment]
@hreintke see pr

**Comment by anakod** [comment]
@raburton, yes you are right :)

**Comment by hreintke** [comment]
@raburton :

THANKS !!! 

I've been looking for this for hours and hours.
