### ISSUE TITLE
Spiffy start address calculation

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#39]
Can be that this issue is generic and not rtos sdk specific.

I have two example applications both use spiffs with a spiffy generated fs.
- httpserver_ajax
  runs OK. flash output : 

```
Writing at 0x00052000... (98 %) 
Writing at 0x00052400... (98 %) 
Writing at 0x00052800... (99 %) 
Writing at 0x00052c00... (99 %) 
Writing at 0x00053000... (100 %) 
Written 300032 bytes in 29.61 seconds (81.05 kbit/s)...
Erasing flash...
head:  12 ;total: 128
erase size :  475136

Writing at 0x00054000... (0 %) 
Writing at 0x00054400... (0 %) 
Writing at 0x00054800... (0 %) 
Writing at 0x00054c00... (0 %) 
Writing at 0x00055000... (0 %) 
```
- CommandProcessing_Debug 
  Fails to start (continuous reset)
  flash output : 

```
Writing at 0x00052c00... (98 %) 
Writing at 0x00053000... (98 %) 
Writing at 0x00053400... (98 %) 
Writing at 0x00053800... (99 %) 
Writing at 0x00053c00... (99 %) 
Writing at 0x00054000... (100 %) 
Written 304128 bytes in 29.96 seconds (81.20 kbit/s)...
Erasing flash...
head:  12 ;total: 128
erase size :  475136

Writing at 0x00054000... (0 %) 
Writing at 0x00054400... (0 %) 
Writing at 0x00054800... (0 %) a
Writing at 0x00054c00... (0 %) 
```

When building commandoutput with DISABLE_SPIFFS it starts OK, (no resets)
It obviously fails when accessing spiffs as it is not flashed with this setting.

To me it looks like a miscalculation of spiffs start address in spiffy.
Any other thought ? If you think it is not I will further investigate into framework calculation of start address and/or other

UPDATE : When locating the spiffs fs manually on another location on the flash and mounting  with a spiffs_mount_manual()  it runs OK

UPDATE 2 : Flash code end as used by framework : _flash_code_end:402545ae

**Comment by alonewolfx2** [comment]
@hreintke this is address calculation problem. spiffy needs right address. i will look into it when i get home.

**Comment by raburton** [comment]
If _flash_code_end is at 402545ae then your spiffs can't start at 54000, because that's before the end of the code. Try flashing it at 55000 instead and see if that works.

**Comment by hreintke** [comment]
Richard,
I have a filesystem on 0x500000, when using spiffs_mount_manual to that it works OK.

The issue is that the spiffy & flash with no DISABLE_SPIFFS in the makefile  flash to the wrong location.
As shown above, not always.Maybe a border case issue.

**Comment by raburton** [comment]
Yes, I understand the issue. It appears you are flashing the filesystem to 0x54000, but _flash_code_end has a value of 0x402545ae, which means there is still code up to 0x545ae and you are overwriting it with the start of your spiffs.

The problem is not in spiffy (it does not know or care where the spiffs is to be located on flash) it is in the makefile where it calculates where to flash the spiffs to. It does this in a very strange way, which looks like it probably only ever works by luck.

**Comment by raburton** [comment]
I reckon something like this would be better:
`SPIFF_START_OFFSET = $(shell printf '0x%X\n' $$(( (($$($(GET_FILESIZE) $(FW_BASE)/0x0a000.bin) - 1) & 0xFFFFF000) + 0x0a000 + 0x01000 )) )`

**Comment by hreintke** [comment]
Just PR'ed the alignment of SPIFFS_OFFSET and spiffs_mount().

There is still a discrepancy in FS size.
makefile project limits the fs depending on SPI_SIZE to max 512K.
spiffs_mount always takes size till end-of-flash.

Will try to resolve when moving to use spiffs USE_MAGIC
