### ISSUE TITLE
Naming of samples

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#42]
The naming of the samples is not very consistent.

@alonewolfx2 : Can you think on what convention we can use and update the samples accordingly ?
Beware that naming is nor only in the 'directory name' but also in the .project and .project files for eclipse.

**Comment by alonewolfx2** [comment]
@hreintke yep. Sorry I was very busy

**Comment by hreintke** [comment]
Need som more thoughts, closing for now.
