### ISSUE TITLE
Main Makefile only for Win$

### ISSUE THREAD

**Issue by laurentppol** [SmingHub/SmingRTOS#7]
1).Main Makefile of Sming_RTOS_POC is written only to support Win$. It does NOT include "guess the OS magic" used in original Sming. 
Env variables working FOR ME:
BIN_HOME=/opt/ESP8266_RTOS_SDK/bin/
ESP_HOME=/opt/esp-open-sdk/
SMING_HOME=/opt/ESP_RTOS_POC/
SDK_BASE=/opt/ESP8266_RTOS_SDK/

With directory structure: /opt/
drwxr-xr-x 10 laurent laurent 4096 01-01 20:00 ESP8266_RTOS_SDK
drwxr-xr-x 10 laurent laurent 4096 01-01 20:53 esp-open-sdk
drwxr-xr-x  9 laurent laurent 4096 10-24 21:11 Espressif
drwxr-xr-x  4 laurent laurent 4096 01-01 17:24 ESP_RTOS_examples
drwxr-xr-x 15 laurent laurent 4096 01-01 19:47 ESP_RTOS_POC
drwxr-xr-x 46 laurent laurent 4096 01-01 19:32 Sming

2). missing ESPTOOL2 (in esp-open-sdk there is esptool.py which did NOT worked for me).

Linux Fedora 16 @ i386 (!64)

**Comment by raburton** [comment]
1) Work fine on Linux, as long as you set appropriate env vars. I'm not aware there are standard paths for rtos sdk yet.
2) esptool2 is not shipped with Sming (original or rtos) and should be download and built separately from the upstream source.
