### ISSUE TITLE
Error compiling Sming_RTOS

### ISSUE THREAD

**Issue by robotiko** [SmingHub/SmingRTOS#8]
Windows: 
It was working, but doesn't coompile with latest code. 

In file included from rboot/appcode/rboot-api.c:18:0:
rboot/appcode/rboot-api.c: In function 'rboot_set_config':
system/mem.h:17:27: error: implicit declaration of function 'pvPortMalloc' [-Werror=implicit-function-declaration]
 #define os_malloc(s)      pvPortMalloc(s, "", 0)
                           ^
rboot/appcode/rboot-api.c:168:19: note: in expansion of macro 'os_malloc'
  buffer = (uint8_)os_malloc(SECTOR_SIZE);
                   ^
system/mem.h:16:27: error: implicit declaration of function 'vPortFree' [-Werror=implicit-function-declaration]
 #define os_free(s)        vPortFree(s, "", 0)
                           ^
rboot/appcode/rboot-api.c:187:2: note: in expansion of macro 'os_free'
  os_free(buffer);
  ^
cc1.exe: all warnings being treated as errors
make: *_\* [build/rboot/appcode/rboot-api.o] Error 1

**Comment by ystrem** [comment]
hi, you have to make edit like below...

hreintke 20:48
for pvPortMalloc and ..Free update C:\Userdata\RTOS_Project\ESP_RTOS_POC\include\esp_systemapi.h lines 75-79
to

```
extern void *pvPortMalloc(size_t xWantedSize, const char *file, uint32 line);
extern void *pvPortZalloc(size_t xWantedSize, const char *file, uint32 line);
//extern void pvPortFree(void *ptr);
extern void vPortFree(void *ptr, const char *file, uint32 line);
extern void *vPortMalloc(size_t xWantedSize);
```
