### ISSUE TITLE
rBoot RTC integration

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#88]
@raburton :

I restarted working on a rBootClass within SmingRTOS, now including your latest update with use of RTC for temp booting.
In order to facilitate that I need to check/access the rBoot RTC data within the rBootClass.
For that I would need to have the option BOOT_RTC_ENABLED within the framework -> added #define BOOT_RVC_ENBLED to sming\include\sming_config.h
Compiles & links unchanged (= not using RTC functions) framework and application OK.

Then including RTC function within rBootClass : 

```
    rboot_rtc_data rbootRTC;

    if (!rboot_get_rtc_data(&rbootRTC))
    {
        commandOutput->printf("No valid rBoot RTC data \r\n");
    }
    else
    {
        commandOutput->printf("rBoot RTC = Next mode : %d, Last mode : %d, Last rom : %d, Temp rom %d\r\n",rbootRTC.next_mode,rbootRTC.last_mode,rbootRTC.last_rom,rbootRTC.temp_rom);
    }
```

Framework compiles OK, application compiles OK but link errors -> `undefined reference to rboot_get_rtc_data`

I expected that I had to include compiling rboot-api.c with the framework -> added `MODULES += rboot/appcode` to the makefile.
But then I hit an "old issue" we had earlier while converting to SmgRTOS -> 

```
rboot/appcode/rboot-api.c:16:22: error: implicit declaration of function 'pvPortMalloc' [-Werror=implicit-function-declaration]
 #define os_malloc(s) pvPortMalloc(s)
                      ^
```

The work in progress (far from complete) is in the RBootClass branch. 

Could you check this and maybe point to a direction/way to solve ?

PS : I did not squash the commit so you can see the last update I did.

**Comment by raburton** [comment]
I'm in Spain at the moment, will have a look when I get back...

**Comment by hreintke** [comment]
Thanks,
Have a nice holiday/working time in probably sunny Spain
