### ISSUE TITLE
RTOS LWIP compile

### ISSUE THREAD

**Issue by hreintke** [SmingHub/SmingRTOS#94]
@Adiea @raburton : 
I have an issue on RTOS with webservers servicing a large number of requests (stop serving pages).
For investigating this further I would need to have LWIP in debug mode.
Asking Espressif on that I get the reply : 

> LWIP is open source on ESP8266_RTOS_SDK_V1.4.0.
> 
> You can enable the debug mode yourself if it is needed.
> 
> Thanks for your interest in ESP8266 !

I lack the knowledge to be able to compile the LWIP from the sources available in the SDK.

Can you help me getting this done so I can continue to trace down the Sming issue ?

**Comment by hreintke** [comment]
@adiea @raburton : 
Managed to compile the lwip. Starting investigation now.

**Comment by ADiea** [comment]
Hi sorry, I'm very short with time cannot help right now
